### ISSUE TITLE
Menu fails to deploy

### ISSUE THREAD

**Issue by tobyak** [xyzaxyz/OctoPrint-Finetunerptr#4]
Menu fails to deploy fully in browser only displaying the top three buttons in a shortened bounding box

**Comment by xyzaxyz** [comment]
Hey,
can you attach a screenshot of this problem please?
I am currently not able to reproduce that error on either my test-instance or the both real OctoPrint 1.3.2 instances I got running.
Also, which version of OctoPrint are you using right now?

**Comment by tobyak** [comment]
![failed to deploy](https://cloud.githubusercontent.com/assets/25429390/25627882/0bcc726e-2f5c-11e7-8225-cf570c4c3fdc.jpg)
Here you go. I have tried other screen resolutions and various iterations of full screen to make it full open, no joy.

**Comment by xyzaxyz** [comment]
Oh, that thing.
I have seen it, yet it's not fixed. The current workaround from this state is, to disconnect -> connect it one more time, so the EEPROM Manager can initialize.
I will fix it this week and push an update :)

**Comment by xyzaxyz** [comment]
Hey,
have you installed the latest update / received an notification about it in your octoprint?
This should fix this problem, so I'll close this issue :)

**Comment by mikeshub** [comment]
This still exists. Does octoprint have to reset the machine for this plugin to work? If so it should just send M503 when the EEPROM Manager is yellow. I tried sending M503 from the console to have it get the eeprom settings, but that didn't work.
